name: google_login_demo
description: Google Sign-In Demo for Flutter

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.0.0
  googleapis: ^13.1.0
  googleapis_auth: ^1.4.0
  http: ^0.13.5
  video_player: ^2.8.1
  path_provider: ^2.1.2
  url_launcher: ^6.2.5
  image_picker: ^1.0.4

flutter:
  uses-material-design: true
